// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";

// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";

//SCREENER
export const SCREENER_FACTORA_LABEL = "FactorA";
export const FACTOR_TIME_UPDATE = "FACTOR_TIME_UPDATE";
export const SCREENER_FACTORB_LABEL = "FactorB";
export const SCREENER_VOLATILITY_LABEL = "Volatility";
export const SCREENER_UPDATE = "SCREENER_UPDATE";
export const INIT_SCR = "INIT_SCR";
export const DEFAULT_SCR = "DEFAULT_SCR";
export const CRYPTO_FILTER_UPDATE = "CRYPTO_FILTER_UPDATE";